version: '3.7'

services:
  postgres:
    container_name: bootcamp_transactions
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: bootcamp_desafio06
